# Results for Logistic Regression when applying syn tranformation to both premise and hypothesis

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

## Loading Results

In [2]:
path_0 = "results/snli/lr/wordnet_p_h_rho_0p0.csv"
path_0p25 = "results/snli/lr/wordnet_p_h_rho_0p25.csv"
path_0p5 = "results/snli/lr/wordnet_p_h_rho_0p5.csv"
path_0p75 = "results/snli/lr/wordnet_p_h_rho_0p75.csv"
path_1 = "results/snli/lr/wordnet_p_h_rho_1p0.csv"

## Results for $\rho = 0$

In [3]:
results = pd.read_csv(path_0)
not_boot_columns = [c for c in results.columns if c.find("boot") == -1]
display(HTML(results[not_boot_columns].to_html()))

## Results for $\rho = 0.25$

In [4]:
results = pd.read_csv(path_0p25)
not_boot_columns = [c for c in results.columns if c.find("boot") == -1]
display(HTML(results[not_boot_columns].to_html()))

## Results for $\rho = 0.5$

In [5]:
results = pd.read_csv(path_0p5)
not_boot_columns = [c for c in results.columns if c.find("boot") == -1]
display(HTML(results[not_boot_columns].to_html()))

## Results for $\rho = 0.75$

In [6]:
results = pd.read_csv(path_0p75)
not_boot_columns = [c for c in results.columns if c.find("boot") == -1]
display(HTML(results[not_boot_columns].to_html()))

## Results for $\rho = 1.0$

In [7]:
results = pd.read_csv(path_1)
not_boot_columns = [c for c in results.columns if c.find("boot") == -1]
display(HTML(results[not_boot_columns].to_html()))